#!/bin/sh /etc/rc.common
START=96
STOP=8
USE_PROCD=1
start_service() {
 role="$(jsonfilter -i /etc/codex-game/endpoint-config.json -e '@.role')"
 case "$role" in home|client) ;; *) return 1;; esac
 procd_open_instance
 procd_set_param command /usr/bin/lua "/usr/libexec/codex-game/endpoint-$role.lua"
 procd_set_param file /etc/codex-game/endpoint-config.json
 procd_set_param respawn 3600 5 0
 procd_set_param stderr 1
 procd_close_instance
}
